using System;
using System.Collections.Generic;
using UnityEngine;

namespace WizardGun
{
    /// <summary>
    /// The boon pool and the rules for what gets offered. Luck drives the rarity roll, which
    /// is most of what makes the Luck stat worth taking.
    ///
    /// The mastery boons are generated by walking <see cref="DamageTypes.Elemental"/> and the
    /// spell categories, so adding a damage school or a spell type gives you its boons for free.
    /// </summary>
    public static class BoonLibrary
    {
        private static List<Boon> _all;

        public static IReadOnlyList<Boon> All
        {
            get
            {
                if (_all == null) BuildPool();
                return _all;
            }
        }

        /// <summary>
        /// Rolls a set of distinct, currently valid boons. <paramref name="rarityBonus"/> is an
        /// extra multiplier on the non-Common tiers, used to make elite rooms pay out better.
        /// </summary>
        public static List<Boon> Offer(RunState run, int count, float rarityBonus = 1f)
        {
            if (_all == null) BuildPool();

            var candidates = new List<Boon>();
            for (int i = 0; i < _all.Count; i++)
                if (_all[i].IsOffered(run)) candidates.Add(_all[i]);

            var chosen = new List<Boon>();
            var used = new HashSet<string>();
            var available = new List<Boon>();

            int guard = 0;
            while (chosen.Count < count && guard++ < 200)
            {
                available.Clear();
                for (int i = 0; i < candidates.Count; i++)
                    if (!used.Contains(candidates[i].Id)) available.Add(candidates[i]);
                if (available.Count == 0) break;

                Rarity rolled = Rarities.Roll(run.Rng, run.Luck, rarityBonus);
                Boon pick = Rarities.PickOfRarity(run.Rng, available, b => b.Rarity, rolled);
                if (pick == null) break;

                used.Add(pick.Id);
                chosen.Add(pick);
            }

            return chosen;
        }

        // ---------------------------------------------------------------- pool

        private static void Add(string id, string name, string description, Rarity rarity, int maxLevel,
            Action<RunState, int> effect, Func<RunState, bool> requirement = null)
        {
            _all.Add(new Boon
            {
                Id = id,
                Name = name,
                Description = description,
                Rarity = rarity,
                MaxLevel = maxLevel,
                Effect = effect,
                Requirement = requirement
            });
        }

        private static void BuildPool()
        {
            _all = new List<Boon>();

            BuildCommon();
            BuildUncommon();
            BuildMasteries();
            BuildRare();
            BuildMythic();
            BuildLegendary();
        }

        // ---------------- common: straightforward numbers

        private static void BuildCommon()
        {
            Add("quickened_step", "Quickened Step", "+10% movement speed.", Rarity.Common, 5,
                (run, level) => run.Sheet.AddPercent(Attr.MoveSpeed, 0.10f, "boon"));

            Add("ironhide", "Ironhide", "+25 maximum health.", Rarity.Common, 5,
                (run, level) => run.Sheet.AddFlat(Attr.MaxHealth, 25f, "boon"));

            Add("sharpshooter", "Sharpshooter", "+12% gun damage.", Rarity.Common, 5,
                (run, level) => run.Sheet.AddPercent(Attr.GunDamage, 0.12f, "boon"));

            Add("arcane_focus", "Arcane Focus", "+12% spell power.", Rarity.Common, 5,
                (run, level) => run.Sheet.AddPercent(Attr.SpellPower, 0.12f, "boon"));

            Add("deep_well", "Deep Well", "+30 maximum mana and +20% mana regeneration.", Rarity.Common, 4,
                (run, level) =>
                {
                    run.Sheet.AddFlat(Attr.MaxMana, 30f, "boon");
                    run.Sheet.AddPercent(Attr.ManaRegen, 0.20f, "boon");
                });

            Add("steady_hands", "Steady Hands", "+25% reload speed.", Rarity.Common, 4,
                (run, level) => run.Sheet.AddPercent(Attr.ReloadSpeed, 0.25f, "boon"));

            Add("cruel_edge", "Cruel Edge", "+6% critical strike chance.", Rarity.Common, 5,
                (run, level) => run.Sheet.AddFlat(Attr.CritChance, 0.06f, "boon"));

            Add("light_feet", "Light Feet", "+15% jump height and +15% air control.", Rarity.Common, 4,
                (run, level) =>
                {
                    run.Sheet.AddPercent(Attr.JumpHeight, 0.15f, "boon");
                    run.Sheet.AddPercent(Attr.AirControl, 0.15f, "boon");
                });
        }

        // ---------------- uncommon: elemental payloads and kill hooks

        private static void BuildUncommon()
        {
            Add("frostbite_rounds", "Frostbite Rounds", "Your bullets chill what they hit.", Rarity.Uncommon, 3,
                (run, level) => run.BulletStatuses.Add(StatusLibrary.Chill(3f, 1)));

            Add("incendiary_rounds", "Incendiary Rounds", "Your bullets set targets burning.", Rarity.Uncommon, 3,
                (run, level) => run.BulletStatuses.Add(StatusLibrary.Burn(3.5f, 1, 4f)));

            Add("venomed_rounds", "Venomed Rounds",
                "Your bullets blight targets, poisoning them and absorbing their healing.", Rarity.Uncommon, 3,
                (run, level) => run.BulletStatuses.Add(StatusLibrary.Blight(6f, 1, 3f)));

            Add("conductive_rounds", "Conductive Rounds",
                "Your bullets shock targets, making them take more damage.", Rarity.Uncommon, 3,
                (run, level) => run.BulletStatuses.Add(StatusLibrary.Shock(4f, 1)));

            Add("withering_rounds", "Withering Rounds", "Your bullets weaken what they hit.", Rarity.Uncommon, 3,
                (run, level) => run.BulletStatuses.Add(StatusLibrary.Weaken(4f, 1)));

            Add("runic_overflow", "Runic Overflow", "Your damaging spells also set targets burning.",
                Rarity.Uncommon, 3,
                (run, level) => run.SpellStatuses.Add(StatusLibrary.Burn(4f, 2, 5f)));

            Add("siphon", "Siphon", "Kills restore 12 mana.", Rarity.Uncommon, 4,
                (run, level) => run.ManaOnKill += 12f);

            Add("bloodfeast", "Bloodfeast", "Kills restore 8 health.", Rarity.Uncommon, 4,
                (run, level) => run.HealOnKill += 8f);

            Add("momentum", "Momentum", "Kills grant a burst of speed for three seconds.", Rarity.Uncommon, 1,
                (run, level) => run.HasteOnKill = true);

            Add("quickened_casting", "Quickened Casting", "Kills shave 0.6s off your spell cooldowns.",
                Rarity.Uncommon, 4,
                (run, level) => run.CooldownReductionOnKill += 0.6f);

            Add("second_wind", "Second Wind", "+2 Vitality, and heal to full right now.", Rarity.Uncommon, 3,
                (run, level) =>
                {
                    run.Sheet.AddStat(StatType.Vitality, 2);
                    run.Player.Health.Heal(run.Player.Health.Max);
                });

            Add("fleet", "Fleet", "+1 dash charge.", Rarity.Uncommon, 3,
                (run, level) => run.Sheet.AddFlat(Attr.DashCharges, 1f, "boon"));

            Add("cold_blood", "Cold Blood", "+20% spell cooldown rate.", Rarity.Uncommon, 4,
                (run, level) => run.Sheet.AddPercent(Attr.CooldownRate, 0.20f, "boon"));
        }

        // ---------------- generated: one mastery per damage school, one per spell category

        private static void BuildMasteries()
        {
            for (int i = 0; i < DamageTypes.Elemental.Length; i++)
            {
                DamageType type = DamageTypes.Elemental[i];   // captured per iteration
                string school = DamageTypes.Name(type);

                Add("mastery_" + type, school + " Mastery",
                    "+18% damage dealt with " + school + ", from any source.", Rarity.Rare, 5,
                    (run, level) => run.Sheet.AddDamagePercent(type, 0.18f, "boon"));

                Add("ward_" + type, school + " Ward",
                    "+15% resistance to incoming " + school + " damage.", Rarity.Uncommon, 4,
                    (run, level) => run.Sheet.AddResistance(type, 0.15f, "boon"));
            }

            SpellType[] categories = (SpellType[])Enum.GetValues(typeof(SpellType));
            for (int i = 0; i < categories.Length; i++)
            {
                SpellType category = categories[i];

                Add("school_" + category, SpellCategoryTitle(category),
                    "+22% effect from your " + category + " spells.", Rarity.Rare, 4,
                    (run, level) => run.Sheet.AddSpellPercent(category, 0.22f, "boon"));
            }
        }

        private static string SpellCategoryTitle(SpellType category)
        {
            switch (category)
            {
                case SpellType.Attack: return "Wrath";
                case SpellType.Mobility: return "Swiftness";
                case SpellType.Control: return "Dominion";
                default: return "Sanctuary";
            }
        }

        // ---------------- rare: build-defining

        private static void BuildRare()
        {
            Add("vampiric_sigil", "Vampiric Sigil", "Heal for 6% of all damage you deal.", Rarity.Rare, 3,
                (run, level) => run.LifestealFraction += 0.06f);

            Add("blink_detonation", "Blink Detonation",
                "Arriving from a Blink detonates an arcane blast.", Rarity.Rare, 3,
                (run, level) =>
                {
                    run.BlinkDetonates = true;
                    // First pick switches it on; later picks make the blast hit harder.
                    if (level > 1) run.BlinkDetonationDamage += 30f;
                },
                // Blink sits on the movement slot now, not in the spell book.
                run => run.Player != null && run.Player.Movement != null &&
                       run.Player.Movement.Has("blink"));

            Add("glass_cannon", "Glass Cannon", "+40% damage dealt, but -25% maximum health.", Rarity.Rare, 3,
                (run, level) =>
                {
                    run.Sheet.AddPercent(Attr.DamageDealt, 0.40f, "boon");
                    run.Sheet.AddPercent(Attr.MaxHealth, -0.25f, "boon");
                });

            Add("overcharge", "Overcharge", "+25% attack speed, but -10% maximum health.", Rarity.Rare, 3,
                (run, level) =>
                {
                    run.Sheet.AddPercent(Attr.AttackSpeed, 0.25f, "boon");
                    run.Sheet.AddPercent(Attr.MaxHealth, -0.10f, "boon");
                });

            Add("bulwark", "Bulwark", "Take 15% less damage from everything.", Rarity.Rare, 3,
                (run, level) => run.Sheet.AddPercent(Attr.DamageTaken, -0.15f, "boon"));

            Add("executioner", "Executioner", "+50% critical damage.", Rarity.Rare, 4,
                (run, level) => run.Sheet.AddPercent(Attr.CritDamage, 0.50f, "boon"));
        }

        // ---------------- mythic: raw stat blocks and broad defences

        private static void BuildMythic()
        {
            Add("titan_grip", "Titan Grip",
                "+3 Strength. Heavier blows, and heavier things you can break.", Rarity.Mythic, 3,
                (run, level) => run.Sheet.AddStat(StatType.Strength, 3));

            Add("scholar", "Scholar", "+3 Intellect.", Rarity.Mythic, 3,
                (run, level) => run.Sheet.AddStat(StatType.Intellect, 3));

            Add("windrunner", "Windrunner", "+3 Agility.", Rarity.Mythic, 3,
                (run, level) => run.Sheet.AddStat(StatType.Agility, 3));

            Add("fortune", "Fortune", "+3 Luck. Better crits, and far better things on offer.",
                Rarity.Mythic, 3,
                (run, level) => run.Sheet.AddStat(StatType.Luck, 3));

            Add("warded_flesh", "Warded Flesh", "+12% resistance to every damage school.", Rarity.Mythic, 3,
                (run, level) =>
                {
                    for (int i = 0; i < DamageTypes.Elemental.Length; i++)
                        run.Sheet.AddResistance(DamageTypes.Elemental[i], 0.12f, "boon");
                });

            Add("arcane_battery", "Arcane Battery",
                "+40% spell cooldown rate and +40 maximum mana.", Rarity.Mythic, 3,
                (run, level) =>
                {
                    run.Sheet.AddPercent(Attr.CooldownRate, 0.40f, "boon");
                    run.Sheet.AddFlat(Attr.MaxMana, 40f, "boon");
                });
        }

        // ---------------- legendary: once in a very long while

        private static void BuildLegendary()
        {
            Add("archmage", "Archmage",
                "Every spell you know gains a level immediately, and always will.", Rarity.Legendary, 3,
                (run, level) =>
                {
                    SpellBook book = run.Player != null ? run.Player.Book : null;
                    if (book == null) return;

                    IReadOnlyList<Spell> known = book.Known;
                    for (int i = 0; i < known.Count; i++) book.LevelUp(known[i]);
                });

            Add("avatar_of_ruin", "Avatar of Ruin",
                "+35% damage dealt with every damage school at once.", Rarity.Legendary, 2,
                (run, level) =>
                {
                    for (int i = 0; i < DamageTypes.Elemental.Length; i++)
                        run.Sheet.AddDamagePercent(DamageTypes.Elemental[i], 0.35f, "boon");
                });

            Add("godspeed", "Godspeed",
                "+30% movement speed, +2 dash charges, and dashes recover far faster.",
                Rarity.Legendary, 2,
                (run, level) =>
                {
                    run.Sheet.AddPercent(Attr.MoveSpeed, 0.30f, "boon");
                    run.Sheet.AddFlat(Attr.DashCharges, 2f, "boon");
                    run.Sheet.AddPercent(Attr.DashSpeed, 0.25f, "boon");
                });
        }
    }
}
