using System;
using System.Collections.Generic;
using UnityEngine;

namespace WizardGun
{
    /// <summary>
    /// The boon pool and the rules for what gets offered. Luck drives the rarity roll, which
    /// is most of what makes the Luck stat worth taking.
    ///
    /// The built-ins live in code so a fresh clone runs with nothing authored. Any
    /// <see cref="BoonAsset"/> found under a Resources folder is merged in: a matching id
    /// replaces the built-in, a new id joins the pool at whatever rarity it declares.
    ///
    /// The mastery boons are generated by walking <see cref="DamageTypes.Elemental"/> and the
    /// spell categories, so adding a damage school or a spell type gives you its boons for free.
    /// </summary>
    public static class BoonLibrary
    {
        private static List<Boon> _all;

        public static IReadOnlyList<Boon> All
        {
            get
            {
                if (_all == null) Build();
                return _all;
            }
        }

        /// <summary>Drops the cached pool so authored assets are picked up again.</summary>
        public static void Reload() => _all = null;

        /// <summary>
        /// Rolls a set of distinct, currently valid boons. <paramref name="rarityBonus"/> is an
        /// extra multiplier on the non-Common tiers, used to make elite rooms pay out better.
        /// </summary>
        public static List<Boon> Offer(RunState run, int count, float rarityBonus = 1f)
        {
            if (_all == null) Build();

            var candidates = new List<Boon>();
            for (int i = 0; i < _all.Count; i++)
                if (_all[i].IsOffered(run)) candidates.Add(_all[i]);

            var chosen = new List<Boon>();
            var used = new HashSet<string>();
            var available = new List<Boon>();

            int guard = 0;
            while (chosen.Count < count && guard++ < 200)
            {
                available.Clear();
                for (int i = 0; i < candidates.Count; i++)
                    if (!used.Contains(candidates[i].Id)) available.Add(candidates[i]);
                if (available.Count == 0) break;

                Rarity rolled = Rarities.Roll(run.Rng, run.Luck, rarityBonus);
                Boon pick = Rarities.PickOfRarity(run.Rng, available, b => b.Rarity, rolled);
                if (pick == null) break;

                used.Add(pick.Id);
                chosen.Add(pick);
            }

            return chosen;
        }

        public static Boon Get(string id)
        {
            for (int i = 0; i < All.Count; i++)
                if (All[i].Id == id) return All[i];
            return null;
        }

        // ---------------------------------------------------------------- pool

        private static void Build()
        {
            // Assigned before merging: anything reading the pool while assets are loading gets
            // the built-ins rather than recursing into a half-built list.
            _all = BuiltIn();

            BoonAsset[] authored = Resources.LoadAll<BoonAsset>("");
            if (authored == null) return;

            for (int i = 0; i < authored.Length; i++)
            {
                Boon boon = authored[i] != null ? authored[i].Boon : null;
                if (boon == null) continue;

                if (string.IsNullOrEmpty(boon.Id))
                {
                    Debug.LogWarning("Boon asset \"" + authored[i].name + "\" has no Id and was ignored.");
                    continue;
                }

                int existing = _all.FindIndex(b => b.Id == boon.Id);
                if (existing >= 0) _all[existing] = boon;
                else _all.Add(boon);
            }
        }

        /// <summary>The code roster. Also what the editor tool seeds new assets from.</summary>
        public static List<Boon> BuiltIn()
        {
            _building = new List<Boon>();

            BuildCommon();
            BuildUncommon();
            BuildMasteries();
            BuildRare();
            BuildMythic();
            BuildLegendary();

            List<Boon> result = _building;
            _building = null;
            return result;
        }

        private static List<Boon> _building;

        private static void Add(string id, string name, string description, Rarity rarity, int maxLevel,
            params BoonEffect[] effects)
        {
            AddGated(id, name, description, rarity, maxLevel, null, effects);
        }

        private static void AddGated(string id, string name, string description, Rarity rarity, int maxLevel,
            BoonRequirement requirement, params BoonEffect[] effects)
        {
            _building.Add(new Boon
            {
                Id = id,
                Name = name,
                Description = description,
                Rarity = rarity,
                MaxLevel = maxLevel,
                Requirement = requirement,
                Effects = new List<BoonEffect>(effects)
            });
        }

        // ---------------- common: straightforward numbers

        private static void BuildCommon()
        {
            Add("quickened_step", "Quickened Step", "+10% movement speed.", Rarity.Common, 5,
                Percent(Attr.MoveSpeed, 0.10f));

            Add("ironhide", "Ironhide", "+25 maximum health.", Rarity.Common, 5,
                Flat(Attr.MaxHealth, 25f));

            Add("sharpshooter", "Sharpshooter", "+12% gun damage.", Rarity.Common, 5,
                Percent(Attr.GunDamage, 0.12f));

            Add("arcane_focus", "Arcane Focus", "+12% spell power.", Rarity.Common, 5,
                Percent(Attr.SpellPower, 0.12f));

            Add("deep_well", "Deep Well", "+30 maximum mana and +20% mana regeneration.", Rarity.Common, 4,
                Flat(Attr.MaxMana, 30f), Percent(Attr.ManaRegen, 0.20f));

            Add("steady_hands", "Steady Hands", "+25% reload speed.", Rarity.Common, 4,
                Percent(Attr.ReloadSpeed, 0.25f));

            Add("light_step", "Light Step", "+15% jump height and +15% air control.", Rarity.Common, 4,
                Percent(Attr.JumpHeight, 0.15f), Percent(Attr.AirControl, 0.15f));
        }

        // ---------------- uncommon: elemental payloads and kill hooks

        private static void BuildUncommon()
        {
            Add("frostbite_rounds", "Frostbite Rounds", "Your bullets chill what they hit.", Rarity.Uncommon, 3,
                Bullets(StatusLibrary.Chill(3f, 1)));

            Add("incendiary_rounds", "Incendiary Rounds", "Your bullets set targets burning.", Rarity.Uncommon, 3,
                Bullets(StatusLibrary.Burn(3.5f, 1, 4f)));

            Add("venomed_rounds", "Venomed Rounds",
                "Your bullets blight targets, poisoning them and absorbing their healing.", Rarity.Uncommon, 3,
                Bullets(StatusLibrary.Blight(6f, 1, 3f)));

            Add("conductive_rounds", "Conductive Rounds",
                "Your bullets shock targets, making them take more damage.", Rarity.Uncommon, 3,
                Bullets(StatusLibrary.Shock(4f, 1)));

            Add("withering_rounds", "Withering Rounds", "Your bullets weaken what they hit.", Rarity.Uncommon, 3,
                Bullets(StatusLibrary.Weaken(4f, 1)));

            Add("runic_overflow", "Runic Overflow", "Your damaging spells also set targets burning.",
                Rarity.Uncommon, 3,
                Spells(StatusLibrary.Burn(4f, 2, 5f)));

            Add("siphon", "Siphon", "Kills restore 12 mana.", Rarity.Uncommon, 4,
                new OnKillEffect { Mana = 12f });

            Add("bloodfeast", "Bloodfeast", "Kills restore 8 health.", Rarity.Uncommon, 4,
                new OnKillEffect { Health = 8f });

            Add("momentum", "Momentum", "Kills grant a burst of speed for three seconds.", Rarity.Uncommon, 1,
                new OnKillEffect { GrantsHaste = true });

            Add("quickened_casting", "Quickened Casting", "Kills shave 0.6s off your spell cooldowns.",
                Rarity.Uncommon, 4,
                new OnKillEffect { CooldownReduction = 0.6f });

            Add("second_wind", "Second Wind", "+2 Vitality, and heal to full right now.", Rarity.Uncommon, 3,
                new ModifyStatEffect { Stat = StatType.Vitality, Points = 2 },
                new FullHealEffect());

            Add("fleet", "Fleet", "+1 dash charge.", Rarity.Uncommon, 3,
                Flat(Attr.DashCharges, 1f));

            Add("cold_blood", "Cold Blood", "+20% spell cooldown rate.", Rarity.Uncommon, 4,
                Percent(Attr.CooldownRate, 0.20f));
        }

        // ---------------- generated: one mastery per damage school, one per spell category

        private static void BuildMasteries()
        {
            for (int i = 0; i < DamageTypes.Elemental.Length; i++)
            {
                DamageType type = DamageTypes.Elemental[i];
                string school = DamageTypes.Name(type);

                Add("mastery_" + type, school + " Mastery",
                    "+18% damage dealt with " + school + ", from any source.", Rarity.Rare, 5,
                    new ModifyDamageSchoolEffect { School = type, Percent = 0.18f });

                Add("ward_" + type, school + " Ward",
                    "+15% resistance to incoming " + school + " damage.", Rarity.Uncommon, 4,
                    new ModifyResistanceEffect { School = type, Amount = 0.15f });
            }

            SpellType[] categories = (SpellType[])Enum.GetValues(typeof(SpellType));
            for (int i = 0; i < categories.Length; i++)
            {
                SpellType category = categories[i];

                Add("school_" + category, SpellCategoryTitle(category),
                    "+22% effect from your " + category + " spells.", Rarity.Rare, 4,
                    new ModifySpellCategoryEffect { Category = category, Percent = 0.22f });
            }
        }

        private static string SpellCategoryTitle(SpellType category)
        {
            switch (category)
            {
                case SpellType.Attack: return "Wrath";
                case SpellType.Mobility: return "Swiftness";
                case SpellType.Control: return "Dominion";
                default: return "Sanctuary";
            }
        }

        // ---------------- rare: build-defining

        private static void BuildRare()
        {
            // Unlocks the alt fires guns keep behind a tier. Levelled rather than a one-off so
            // it can stay in the pool, and so the strongest right clicks arrive last.
            Add("gunsmith", "Gunsmith's Kit",
                "Unlocks the next tier of locked alt fires. Right click uses a gun's alt fire.",
                Rarity.Rare, 2,
                new AltFireTierEffect());

            Add("vampiric_sigil", "Vampiric Sigil", "Heal for 6% of all damage you deal.", Rarity.Rare, 3,
                new LifestealEffect { Fraction = 0.06f });

            AddGated("blink_detonation", "Blink Detonation",
                "Arriving from a Blink detonates an arcane blast.", Rarity.Rare, 3,
                // Blink sits on the movement slot now, not in the spell book.
                new HasMovementAbilityRequirement { AbilityId = "blink" },
                new BlinkDetonationEffect { BonusDamagePerExtraLevel = 30f });

            Add("glass_cannon", "Glass Cannon", "+40% damage dealt, but -25% maximum health.", Rarity.Rare, 3,
                Percent(Attr.DamageDealt, 0.40f), Percent(Attr.MaxHealth, -0.25f));

            Add("overcharge", "Overcharge", "+25% attack speed, but -10% maximum health.", Rarity.Rare, 3,
                Percent(Attr.AttackSpeed, 0.25f), Percent(Attr.MaxHealth, -0.10f));

            Add("bulwark", "Bulwark", "Take 15% less damage from everything.", Rarity.Rare, 3,
                Percent(Attr.DamageTaken, -0.15f));

            Add("executioner", "Executioner", "+50% critical damage.", Rarity.Rare, 4,
                Percent(Attr.CritDamage, 0.50f));
        }

        // ---------------- mythic: raw stat blocks and broad defences

        private static void BuildMythic()
        {
            Add("titan_grip", "Titan Grip",
                "+3 Strength. Heavier blows, and heavier things you can break.", Rarity.Mythic, 3,
                new ModifyStatEffect { Stat = StatType.Strength, Points = 3 });

            Add("scholar", "Scholar", "+3 Intellect.", Rarity.Mythic, 3,
                new ModifyStatEffect { Stat = StatType.Intellect, Points = 3 });

            Add("windrunner", "Windrunner", "+3 Agility.", Rarity.Mythic, 3,
                new ModifyStatEffect { Stat = StatType.Agility, Points = 3 });

            Add("fortune", "Fortune", "+3 Luck. Better crits, and far better things on offer.",
                Rarity.Mythic, 3,
                new ModifyStatEffect { Stat = StatType.Luck, Points = 3 });

            Add("warded_flesh", "Warded Flesh", "+12% resistance to every damage school.", Rarity.Mythic, 3,
                new ModifyResistanceEffect { AllElemental = true, Amount = 0.12f });

            Add("arcane_battery", "Arcane Battery",
                "+40% spell cooldown rate and +40 maximum mana.", Rarity.Mythic, 3,
                Percent(Attr.CooldownRate, 0.40f), Flat(Attr.MaxMana, 40f));
        }

        // ---------------- legendary: once in a very long while

        private static void BuildLegendary()
        {
            Add("archmage", "Archmage",
                "Every spell you know gains a level immediately, and always will.", Rarity.Legendary, 3,
                new LevelUpKnownSpellsEffect());

            Add("avatar_of_ruin", "Avatar of Ruin",
                "+35% damage dealt with every damage school at once.", Rarity.Legendary, 2,
                new ModifyDamageSchoolEffect { AllElemental = true, Percent = 0.35f });

            Add("godspeed", "Godspeed",
                "+30% movement speed, +2 dash charges, and dashes recover far faster.",
                Rarity.Legendary, 2,
                Percent(Attr.MoveSpeed, 0.30f), Flat(Attr.DashCharges, 2f), Percent(Attr.DashSpeed, 0.25f));
        }

        // ---------------- shorthands
        //
        // The roster is read far more often than it is written, and these cover most of it.
        // Anything more elaborate spells out its effect object in full.

        private static ModifyAttributeEffect Percent(Attr attr, float amount) =>
            new ModifyAttributeEffect { Attribute = attr, Mode = ModifierMode.Percent, Amount = amount };

        private static ModifyAttributeEffect Flat(Attr attr, float amount) =>
            new ModifyAttributeEffect { Attribute = attr, Mode = ModifierMode.Flat, Amount = amount };

        private static AddOnHitStatusEffect Bullets(StatusApplication status) =>
            new AddOnHitStatusEffect { Status = status, OnSpells = false };

        private static AddOnHitStatusEffect Spells(StatusApplication status) =>
            new AddOnHitStatusEffect { Status = status, OnSpells = true };
    }
}
